### ISSUE TITLE
I cannot find the code or exe for Windows on Github

### ISSUE THREAD

**Issue by rpherman** [aiekick/NoodlesPlate#15]
I looked through the repository, and I cannot find Noodlesplate source or builds. It looks great!

**Comment by aiekick** [comment]
there is no source code, but you can found binaries here : https://github.com/aiekick/NoodlesPlate/releases. 

Availble also from the main page in the repo header when you have commits, branch, packages and releases :)

**Comment by rpherman** [comment]
Thanks! Not new to Github, but not a big user of it either, so thank you for pointing out the obvious! Looking forward to trying it.

**Comment by aiekick** [comment]
np haha
