### ISSUE TITLE
Wrong screen resolution on Windows 10

### ISSUE THREAD

**Issue by jarble** [aiekick/NoodlesPlate#16]
When I open NoodlesPlate on Windows 10, the window appears to have the wrong resolution. The text is almost too small to read:
![image](https://user-images.githubusercontent.com/1735311/143309753-05bb126e-5549-42cb-95ae-bafeb74b7ed6.png)
Is it possible to change the resolution of this window?

**Comment by aiekick** [comment]
ho, weird bug. never have this one.

you can use ctrl + mouse wheel on each ui side for the moment. but its not normla to have this issue.

what is you screen res ? High dpi screen i guess ?

**Comment by aiekick** [comment]
you can try the last release of today : https://github.com/aiekick/NoodlesPlate/releases/tag/v0.5.937

i have added a global ui scale slider available in the settings dialog.
i have also added a check for enable/disable the support of HDPi screen. but wip btw since, i have not any HDPI monitors)
