### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by WindowsNT** [aiekick/NoodlesPlate#17]
I 'd like to include your work in my video editor as a plugin to edit shaders. Can we work that out? It's not very much clear from your license what I may do. 

Good job btw.
Best,

**Comment by aiekick** [comment]
Hello,

Yes you van use it even if included as a freeware and explained like that in a commercial package.

Just you cant claim its your propietary software.
You cant sell it as your software like if you defined a price for this tool.

All mit objets are like that. Ndp use many mit lib by ex, and i could sell it if i would like. But its not what i want

So you must join with your package the license of ndp too.

You have many site who can explain mit licenses i guess too

**Comment by aiekick** [comment]
its ok ?

**Comment by WindowsNT** [comment]
Sure.  We can perhaps talk about a partnership, I 'm interested in your shaders.

**Comment by aiekick** [comment]
no mush time for that but why not. you can contact me by mail (see my profil page)
