### ISSUE TITLE
Crash on Windows 8?

### ISSUE THREAD

**Issue by sy2002** [aiekick/NoodlesPlate#2]
As a Mac User, I tried to run the x86 version in in my Windows 8 32bit under Parallels. It crashed with the following message:

```
Error 65543: WGL: Failed to create OpenGL context
Error 65538: Cannot set swap interval without a current OpenGL or OpenGL ES context
```

OpenGL in general is available on my Virtual machine. For checking, I tested it by running my own [syfluid,](https://sourceforge.net/projects/syfluid/?source=directory) which also uses GLSL shaders. This worked.

Do I maybe need some additional DLLs? Or is maybe Windows 8 just too old?

BTW: Do you plan a portable version that supports Mac? (And Linux) :-)

(Screenshot attached)
<img width="437" alt="2019-03-24_12-40-04" src="https://user-images.githubusercontent.com/6825267/54878915-35894d00-4e33-11e9-95e6-18abd62943a1.png">

**Comment by aiekick** [comment]
NoodlesPlate require Opengl 4.2 mini. maybe it is the problem ?

i have planned to do at some point a linux version. but not mac. (i have nothing to dev on mac)

**Comment by sy2002** [comment]
You are right: My Windows 8 machine only has OpenGL 3.3.

So I guess it makes sense to close this issue (did it), but you might want to have a "if OpenGL < 4.2" line to prevent a crash :-)

**Comment by aiekick** [comment]
for the next release, i will reactivate the version mini to opengl 3.2. opengl 4.2 was needed for compute shaders only. so i can deactivate compute shader when 3.2 supported only.

and yes i will close the app when opengl 3.2 not possible with a message in console :)

thanks
